
connexion:
    path:    /
    defaults:  {_controller: ccGestionFraisBundle:Default:index}
    
visiteur:
    path:    /visiteur
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:index}
    
saisieFiche:
    path:    /visiteur/saisie
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:saisie}
    
traiterFrais:
    path:   /visiteur/traiterFrais
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:traiterFrais}
    
supprFrais:
    path:   /visiteur/supprFrais
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:supprimerFrais}
    
creerFrais:
    path:   /visiteur/creerFrais
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:creerFrais}
    
consulterFrais:
    path:    /visiteur/voirFrais
    defaults: {_controller: ccGestionFraisBundle:Visiteur:consulterFrais}
    
consulterUnFrais:
    path:    /visiteur/voirFrais/{mois}
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:consulterUnFrais}
    requirements:
        mois : \d{6}