
connexion:
    path:    /
    defaults:  {_controller: ccGestionFraisBundle:Default:index}
    
deconnexion:
    path:    /deco
    defaults:  {_controller: ccGestionFraisBundle:Default:deconnexion}
   
    
visiteur:
    path:    /visiteur
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:index}
    
saisieFiche:
    path:    /visiteur/saisie
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:saisie}
    
traiterFrais:
    path:   /visiteur/traiterFrais
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:traiterFrais}
    
supprFrais:
    path:   /visiteur/supprFrais
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:supprimerFrais}
    
creerFrais:
    path:   /visiteur/creerFrais
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:creerFrais}
    
consulterFrais:
    path:    /visiteur/voirFrais
    defaults: {_controller: ccGestionFraisBundle:Visiteur:consulterFrais}
    
consulterUnFrais:
    path:    /visiteur/voirFrais/{mois}
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:consulterUnFrais}
    requirements:
        mois : \d{6}


comptable:
    path:    /comptable
    defaults:  {_controller: ccGestionFraisBundle:Comptable:index}
    
validerFiches:
    path:    /comptable/FichesAValider
    defaults:  {_controller:  ccGestionFraisBundle:Comptable:validerFiches}

consulterFiche:
    path:    /comptable/consulter/{idVis}-{mois}
    defaults: {_controller: ccGestionFraisBundle:Comptable:consulterFiche}
    requirements:
        isVis: \d+
        mois: \d{6}

supprimerFrais:
    path:    /comptable/supprFrais/{id}
    defaults:  {_controller:  ccGestionFraisBundle:Comptable:supprimerFrais}
    requirements:
        id: \d+
        
validerFiche:
    path: /comptable/valider/{idVis}-{mois}
    defaults: {_controller: ccGestionFraisBundle:Comptable:validerFiche}
    requirements:
        isVis: \d+
        mois: \d{6}

suivre:
    path: /comptable/suivre
    defaults: {_controller: ccGestionFraisBundle:Comptable:suivreFiches}

vueFicheRemboursement:
    path:    /comptable/fiche/{idVis}-{mois}
    defaults: {_controller: ccGestionFraisBundle:Comptable:vueFicheRemboursement}
    
rembourserFiche:
    path:    /comptable/remboursement/{idVis}-{mois}
    defaults:  {_controller:  ccGestionFraisBundle:Comptable:rembourserFiche}

reporterFrais:
    path:    /comptable/reporter-frais/{id}
    defaults:  {_controller:  ccGestionFraisBundle:Comptable:reporterFrais}
    requirements:
        id: \d+