cc_gestion_frais_homepage:
    path:     /hello/{name}
    defaults: { _controller: ccGestionFraisBundle:Default:index }

connexion:
    path:    /
    defaults:  {_controller: ccGestionFraisBundle:Default:index}
    
visiteur:
    path:    /visiteur
    defaults:  {_controller: ccGestionFraisBundle:Visiteur:index}