<?php

namespace cc\GestionFraisBundle\Entity;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function trouverVisiteur($login, $mdp){
        
        $unVisiteur = $this->createQueryBuilder('v')
                ->where('v.login = :login')
                ->setParameter('login', $login)
                ->andWhere('v.mdp = :mdp')
                ->setParameter('mdp', $mdp)
                ->getQuery()
                ->getOneOrNullResult();
        return $unVisiteur;
    }
    
}
